import React from "react";
import Layout from "components/layout";
import { Box } from "theme-ui";

export default function PageTest() {
  return (
    <Layout>
      <Box sx={{ pt: "110px" }}>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
        <h1>Une simple page de test</h1>
      </Box>
    </Layout>
  );
}
